// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tspldgkwlwtsbzrfeqya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcGxkZ2t3bHd0c2J6cmZlcXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzU0ODAsImV4cCI6MjA2NDgxMTQ4MH0.ycjJabhYN5r_dGxRELqNVA9-8i8SW3xIXkAAQPh3H4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);